// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class GPGSIds
{
        public const string achievement_man_in_black = "CgkI4bKFrL4IEAIQDQ"; // <GPGSID>
        public const string achievement_thousand = "CgkI4bKFrL4IEAIQBA"; // <GPGSID>
        public const string leaderboard_high_score = "CgkI4bKFrL4IEAIQAQ"; // <GPGSID>
        public const string achievement_newbie = "CgkI4bKFrL4IEAIQCQ"; // <GPGSID>
        public const string achievement_buyer = "CgkI4bKFrL4IEAIQBQ"; // <GPGSID>
        public const string achievement_without_help = "CgkI4bKFrL4IEAIQBw"; // <GPGSID>
        public const string achievement_higher_and_higher = "CgkI4bKFrL4IEAIQDA"; // <GPGSID>
        public const string achievement_dont_miss_it = "CgkI4bKFrL4IEAIQCA"; // <GPGSID>
        public const string achievement_professional_killer = "CgkI4bKFrL4IEAIQCg"; // <GPGSID>
        public const string achievement_is_it_dangerous = "CgkI4bKFrL4IEAIQBg"; // <GPGSID>
        public const string achievement_your_first_time = "CgkI4bKFrL4IEAIQAg"; // <GPGSID>
        public const string achievement_insane_killer = "CgkI4bKFrL4IEAIQCw"; // <GPGSID>
        public const string achievement_time_to_go_shopping = "CgkI4bKFrL4IEAIQAw"; // <GPGSID>

}

